FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs

COPY . .
WORKDIR /app/website

RUN npm install

EXPOSE 8081

ENTRYPOINT ["dotnet", "watch", "run", "--project", "/app/website/website.csproj", "--no-launch-profile", "--urls", "http://+:8081"]